---
var_1: '''production'' inventory, ''all'' group'
var_2: '''production'' inventory, ''all'' group'
var_3: '''production'' inventory, ''all'' group'
var_3_1: '''production'' inventory, ''all'' group'
var_3_2: '''production'' inventory, ''all'' group'